sudo: required
language: rust
rust:
- 1.25.0
services:
- docker
env:
  global:
  - secure: lMLSfOuCT3bwcOgVXJ8b5ac+q2YoYqN2KBa37Y8ipPQmeLAmkGXR3fqEmfVNMSlhmRIi67KdBKPUshcY7KSZ6h2qC9ord05Vqk9gWlC9w/TDkY5EfEHgIRGZGS1min/qao5doz9vtu70v7CC93F7c7hPE0Z9MLfWPxvmQaAKw7CnTVREBQ9gaR51L29ALsEP9knOnTGW17mTl/l1OS6TxnybWnWIMNJCe+ZKOriAOWBIyMieYIudRJwJFJOgPtvy0d1saplbxfLbAedO5kmpv3eoUXJb22Cv3gglmVrkOcN5s9jq38XCmEzZW6ZOTcrWtNgyb1Qz0DPLkNhNDbW8D6xtVe5LFm+iW3gJqG3JNDFF288POQ/NgFi90OR24hpz2BXoV7xJJ9A4nAT9X6I6vlqdpgFMUtQ64X6f2EEMNtoa3CEYUPbNuT6O7Z6PZX00bKj2MU5vqT28RWGzQ5xoIeAexnEHKW4t3gcoP8xHWVu88MnHQ5zjED+UMsMRD80Wr+ouo8aRTqKpPKnMBxb6Mj46y+0rC/oHkaZ2XZhHnwfaC6NEioeTPsRSsoDti+RbJh5fLB5BjQ7EyIjignyx7K7uACAmNpHsSeM139pT2CgNtMHHbIudlz9n7oNh03c0LFurKxgdTtKL+9+zgidrQbe5tVNQiMy5QJsu48RR1/I= #DOCKER_EMAIL
  - secure: ZLEGr3DpqCeTrs4ZI0KeGYMMFR6Zkizpj73c++Gff1KMr1GNbJaXDQ00SeQNV7iVKsiUA9OAd5z2+Mg3mwVcEdASBxcWdbF1tD6oHEFboC7j76BKLXFGrYN34HVTm4vHsCY5c814wJLA0MX5GNfsfrc8+JcTTNywaUfqO0e4PZ8Ho2dU5z4bf409ISFeRo4cMvyX6v/S4rzbUWJIycOQYRmGct1wBTpuj4De51abfVwDqcTMd5j1g4kPfeoAmTo1NBu2JEvG2yjsESvTejYbsHx4t18p/V2ZP5qivoYqF7ffs32TYQIBwu1V910BosZ8j53pBCb1lhS/txu/RKxA6u+Z6jpozNpc+Vy4Z7+ZoblyX1c0pJpMoHd0QH5vGCCearCHbFV9HS4yjg7VjrTBT6indfIlgJc1dRX18KUKCmtvBfzaYsYR/DY9gFHXXBKu7Nra0qKMICoF6jLrb73O72yr/AUPDHbM4l9CBwKByNfEuawwUHH68zKDr2TkfZyF5VYhfjcsR2U7N1ZG6EoFMAsYQmtUA9DixrNAGdSI+EA6I5aaBRhZOfKMgTKvJZ7KNysKcfGwukDpwGN02RpLGwjRQuO8NrCY06xWkRyQyyM312zlqxGc5k79dkMWa2T6f/a3R2euTxKCn2Ec7WD7pzoRnFmkmGVq2J1Ifvbp1Es= #DOCKER_USER
  - secure: Rx6A4MjxjZmvf+7ozZSo31LSSaWAowtFBpZyzGpoZZXYPf2Dm/Oot96RTNDiA6KIpYswMCb3g9RqYduJeMVshZ3Z6sEi56+Mc91ZEeCPHfpOXOxmbUyiJOZ5yPBV5i54MrucuNaPH2K8CA/ph+p5/Vg7v84J5ARLJT0HpnC/c6cdqrFLcNfOJK8i8WTMnEXu0CHYzfPod16VEp9dAXOW7VnTM3aoP+4lheD3vesISWTYD9KpBjQGeRHSiSVfiQHVxgLfYFHNoRVWqlCNiUcT8KO71ZPk61hqCvf0kbIAUEPF1mxvtzPukQNyj8ML62IrOhjt7zsb0EPYIZ2zyorG9JAgPdfcKwFSUp07upjhU/uDbk/JODntQDpy9OtPPSeskngZfbztQAJMuBLtIXVwRmineXObUhLmWYaNSIxbbXGn8zn2qFJK/E44IsW1PRpAPkjOfCCvu14LAw8H7XHHbYJRGu+47RNGw0iQcH60C5EWKr6f0jtpQ9dGOUlrm91MH+BpJ9c3Frh3hr6EyAIEhUmkBXraufu01NCmec8I7A7ZLT57gXrfFlm6BI/xrgrF4cIzQDMJKCNtCCjeFtfiM+j5ONP5WPmUpWKFV2ZSkS/CF03Ej2XgqG99muf/++vLpnGlpVrIak1Y+lV8z4/WWol3KlMfckc2Jk+NED2C3do= #DOCKER_PASS
  - COMMIT=${TRAVIS_COMMIT::8}
script:
- cargo build --verbose
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- export REPO=$DOCKER_USER/rust-basic-http-server
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
